// home/src/single-card/single-card.tsx
import ScrollView from 'devextreme-react/scroll-view';
import './single-card.css';

export default ({ title, description, children }) => (
  <ScrollView height={'100%'} width={'100%'} className={'with-footer single-card'}>
    <div className={'dx-card content'}>
      <div className={'header'}>
        <div className={'title'}>{title}</div>
        <div className={'description'}>{description}</div>
      </div>
      {children}
    </div>
  </ScrollView>
);

// auth/src/app/single-card/single-card.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-single-card',
  templateUrl: './single-card.component.html',
  styleUrls: ['./single-card.component.scss']
})
export class SingleCardComponent {

  @Input() 
  title!: string;

  @Input()
  description!: string;
  
  constructor() { }

}

<dx-scroll-view height="100%" width="100%" class="with-footer single-card">
    <div class="dx-card content">
      <div class="header">
        <div class="title">{{title}}</div>
        <div class="description">{{description}}</div>
      </div>
      <ng-content></ng-content>
    </div>
  </dx-scroll-view>
